"use client";

import { useState } from "react";
import EmergencyCard from "@/components/EmergencyCard";
import type { EmergencyCardData } from "@/lib/emergencyCard";

type Lang = "zh" | "en";

interface GuidanceResponse {
  kind: "guidance";
  urgency: "immediate" | "today" | "next_appointment";
  urgency_label: string;
  explanation_native: string;
  explanation_source: string;
  english_script: string;
  contact_type: string;
  contact_label: string;
  disclaimer: string;
  source?: "glm" | "gemini" | "none";
}

interface EmergencyResponse {
  kind: "emergency";
  matched_term: string;
  contact_type: string;
  card: EmergencyCardData;
  disclaimer: string;
}

interface FallbackResponse {
  kind: "fallback";
  message: string;
  contact_type: string;
  disclaimer: string;
}

type ExpressResponse = GuidanceResponse | EmergencyResponse | FallbackResponse;

const UI = {
  en: {
    title: "Express a symptom",
    subtitle: "Describe how you feel. We give you an English script to show your midwife.",
    placeholder: "e.g. I have mild back pain",
    submit: "Get my script",
    loading: "Preparing…",
    urgencyHeading: "Urgency",
    scriptHeading: "Say or play this to your midwife",
    contactHeading: "Who to contact",
    sourceHeading: "Based on",
    privacy: "Your words are not stored.",
    again: "Start again",
    error: "Something went wrong. Please try again.",
    genGlm: "Generated by GLM-5.1",
    genGemini: "Generated by Gemini (fallback)",
  },
  zh: {
    title: "表达症状",
    subtitle: "描述您的感受，我们会为您准备一段英文台词，供您展示给助产士。",
    placeholder: "例如：我有轻微背痛",
    submit: "获取我的台词",
    loading: "准备中…",
    urgencyHeading: "紧急程度",
    scriptHeading: "向助产士说出或播放这段话",
    contactHeading: "联系谁",
    sourceHeading: "依据",
    privacy: "您的内容不会被保存。",
    again: "重新开始",
    error: "出现问题，请重试。",
    genGlm: "由 GLM-5.1 生成",
    genGemini: "由 Gemini 生成（备用）",
  },
} as const;

const URGENCY_STYLES: Record<
  GuidanceResponse["urgency"],
  { bar: string; chip: string; icon: string }
> = {
  immediate: { bar: "border-urgent", chip: "bg-urgent text-white", icon: "!" },
  today: { bar: "border-soon", chip: "bg-soon text-white", icon: "▲" },
  next_appointment: { bar: "border-routine", chip: "bg-routine text-white", icon: "✓" },
};

export default function ExpressFlow() {
  const [lang, setLang] = useState<Lang>("en");
  const [text, setText] = useState("");
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState<ExpressResponse | null>(null);
  const [error, setError] = useState(false);

  const t = UI[lang];

  async function onSubmit(e: React.FormEvent) {
    e.preventDefault();
    if (!text.trim() || loading) return;
    setLoading(true);
    setError(false);
    setResult(null);
    try {
      const res = await fetch("/api/express", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ text, lang, source: "text" }),
      });
      const data = (await res.json()) as ExpressResponse;
      setResult(data);
    } catch {
      setError(true);
    } finally {
      setLoading(false);
    }
  }

  function reset() {
    setResult(null);
    setText("");
    setError(false);
  }

  if (result?.kind === "emergency") {
    return <EmergencyCard card={result.card} />;
  }

  return (
    <section className="w-full max-w-device space-y-4">
      <div className="flex items-center justify-between">
        <h2 className="text-lg font-bold text-slate-900">{t.title}</h2>
        <div className="flex overflow-hidden rounded-full border border-slate-300 text-sm">
          <button
            type="button"
            onClick={() => setLang("en")}
            className={`px-3 py-1 ${lang === "en" ? "bg-slate-900 text-white" : "text-slate-600"}`}
            aria-pressed={lang === "en"}
          >
            EN
          </button>
          <button
            type="button"
            onClick={() => setLang("zh")}
            className={`px-3 py-1 ${lang === "zh" ? "bg-slate-900 text-white" : "text-slate-600"}`}
            aria-pressed={lang === "zh"}
          >
            中文
          </button>
        </div>
      </div>

      <p className="text-sm text-slate-600">{t.subtitle}</p>

      <form onSubmit={onSubmit} className="space-y-3">
        <textarea
          value={text}
          onChange={(e) => setText(e.target.value)}
          placeholder={t.placeholder}
          rows={3}
          className="w-full resize-none rounded-xl border border-slate-300 p-3 text-base text-slate-900 focus:border-slate-500 focus:outline-none"
        />
        <button
          type="submit"
          disabled={loading || !text.trim()}
          className="w-full rounded-xl bg-slate-900 px-4 py-3 text-base font-semibold text-white disabled:opacity-40"
        >
          {loading ? t.loading : t.submit}
        </button>
      </form>

      <p className="text-center text-xs text-slate-400">{t.privacy}</p>

      {error && <p className="rounded-lg bg-red-50 p-3 text-sm text-urgent">{t.error}</p>}

      {result?.kind === "guidance" && (
        <article className={`space-y-4 rounded-2xl border-l-4 bg-white p-4 shadow-sm ${URGENCY_STYLES[result.urgency].bar}`}>
          <div>
            <p className="text-xs font-semibold uppercase tracking-wide text-slate-400">
              {t.urgencyHeading}
            </p>
            <span
              className={`mt-1 inline-flex items-center gap-2 rounded-full px-3 py-1 text-sm font-semibold ${URGENCY_STYLES[result.urgency].chip}`}
            >
              <span aria-hidden="true">{URGENCY_STYLES[result.urgency].icon}</span>
              {result.urgency_label}
            </span>
          </div>

          <p className="whitespace-pre-line text-base leading-relaxed text-slate-900">
            {result.explanation_native}
          </p>

          <div className="rounded-xl bg-slate-50 p-3">
            <p className="text-xs font-semibold uppercase tracking-wide text-slate-400">
              {t.scriptHeading}
            </p>
            <p className="mt-1 text-base font-medium text-slate-900">{result.english_script}</p>
          </div>

          <div>
            <p className="text-xs font-semibold uppercase tracking-wide text-slate-400">
              {t.contactHeading}
            </p>
            <p className="mt-1 text-sm font-semibold text-slate-900">{result.contact_label}</p>
          </div>

          <p className="text-xs text-slate-500">
            <span className="font-semibold">{t.sourceHeading}:</span> {result.explanation_source}
          </p>

          {result.source && result.source !== "none" && (
            <p className="text-[11px] text-slate-400">
              {result.source === "gemini" ? t.genGemini : t.genGlm}
            </p>
          )}

          <p className="border-t border-slate-100 pt-3 text-xs font-medium text-slate-500">
            {result.disclaimer}
          </p>

          <button
            type="button"
            onClick={reset}
            className="text-sm font-semibold text-slate-600 underline"
          >
            {t.again}
          </button>
        </article>
      )}

      {result?.kind === "fallback" && (
        <article className="space-y-3 rounded-2xl border-l-4 border-soon bg-white p-4 shadow-sm">
          <p className="text-base text-slate-900">{result.message}</p>
          <p className="text-sm font-semibold text-slate-900">{result.contact_type}</p>
          <p className="border-t border-slate-100 pt-3 text-xs font-medium text-slate-500">
            {result.disclaimer}
          </p>
          <button
            type="button"
            onClick={reset}
            className="text-sm font-semibold text-slate-600 underline"
          >
            {t.again}
          </button>
        </article>
      )}
    </section>
  );
}
