"use client";

import { useRef, useState } from "react";
import EmergencyCard from "@/components/EmergencyCard";
import type { EmergencyCardData } from "@/lib/emergencyCard";

type Lang = "zh" | "en";

interface InterpretationResponse {
  kind: "interpretation";
  document_type: string;
  explanation_native: string;
  explanation_en: string;
  explanation_source: string;
  next_steps: string[];
  questions_en: string[];
  disclaimer: string;
  source?: "glm" | "gemini" | "none";
  offline?: boolean;
}

interface EmergencyResponse {
  kind: "emergency";
  matched_term: string;
  contact_type: string;
  card: EmergencyCardData;
  disclaimer: string;
}

interface FallbackResponse {
  kind: "fallback";
  message: string;
  disclaimer: string;
}

type InterpretResponse =
  | InterpretationResponse
  | EmergencyResponse
  | FallbackResponse;

const UI = {
  en: {
    title: "Interpret a letter",
    subtitle: "Paste NHS correspondence. We explain it in plain language and the questions to ask.",
    placeholder: "Paste the text of your NHS letter or result here",
    submit: "Explain this letter",
    loading: "Reading…",
    typeHeading: "Document",
    explanationHeading: "What this means",
    englishHeading: "In English",
    stepsHeading: "Next steps",
    questionsHeading: "Questions to ask your midwife",
    sourceHeading: "Based on",
    privacy: "Your letter is not stored.",
    again: "Start again",
    error: "Something went wrong. Please try again.",
    genGlm: "Generated by GLM-5.1",
    genGemini: "Generated by Gemini (fallback)",
    offline: "Example (offline)",
    photo: "Photograph the letter",
    photoReading: "Reading photo…",
    photoConfirm:
      "Text extracted from your photo — please check it matches the letter, then continue.",
    photoRetake: "Retake photo",
    photoTypeInstead: "Or type/paste the letter below.",
    photoPrivacy: "The photo is read once and never stored.",
  },
  zh: {
    title: "解读信件",
    subtitle: "粘贴 NHS 信件，我们会用简明语言为您解释，并列出可以询问的问题。",
    placeholder: "在此粘贴您的 NHS 信件或检查结果文本",
    submit: "解读这封信",
    loading: "阅读中…",
    typeHeading: "文件类型",
    explanationHeading: "这是什么意思",
    englishHeading: "英文说明",
    stepsHeading: "接下来的步骤",
    questionsHeading: "可向助产士询问的问题",
    sourceHeading: "依据",
    privacy: "您的信件不会被保存。",
    again: "重新开始",
    error: "出现问题，请重试。",
    genGlm: "由 GLM-5.1 生成",
    genGemini: "由 Gemini 生成（备用）",
    offline: "示例（离线）",
    photo: "拍摄信件照片",
    photoReading: "正在读取照片…",
    photoConfirm: "已从照片中提取文字——请核对与信件内容一致后再继续。",
    photoRetake: "重新拍摄",
    photoTypeInstead: "或在下方输入/粘贴信件内容。",
    photoPrivacy: "照片仅读取一次，不会被保存。",
  },
} as const;

/** Client-side cap, mirrors the route's ~8MB decoded limit. */
const MAX_PHOTO_BYTES = 8 * 1024 * 1024;

export default function InterpretFlow() {
  const [lang, setLang] = useState<Lang>("en");
  const [text, setText] = useState("");
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState<InterpretResponse | null>(null);
  const [error, setError] = useState(false);
  const [ocrLoading, setOcrLoading] = useState(false);
  const [ocrError, setOcrError] = useState<string | null>(null);
  const [ocrConfirm, setOcrConfirm] = useState(false);
  const fileInputRef = useRef<HTMLInputElement>(null);

  const t = UI[lang];

  async function onPhotoChosen(e: React.ChangeEvent<HTMLInputElement>) {
    const file = e.target.files?.[0];
    // Allow re-selecting the same file on Retake.
    e.target.value = "";
    if (!file || ocrLoading || loading) return;

    setOcrError(null);
    setOcrConfirm(false);
    if (!file.type.startsWith("image/") || file.size > MAX_PHOTO_BYTES) {
      setOcrError(t.error);
      return;
    }

    setOcrLoading(true);
    try {
      const dataUrl = await new Promise<string>((resolve, reject) => {
        const reader = new FileReader();
        reader.onload = () => resolve(String(reader.result));
        reader.onerror = () => reject(reader.error);
        reader.readAsDataURL(file);
      });
      const imageBase64 = dataUrl.slice(dataUrl.indexOf(",") + 1);

      const res = await fetch("/api/ocr", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ imageBase64, mimeType: file.type }),
      });
      const data = (await res.json().catch(() => null)) as
        | { text?: string; error?: string }
        | null;

      if (res.ok && data?.text) {
        // Confirmation step (PRD §11.7): extracted text lands in the textarea
        // for the user to check/edit BEFORE they press "Explain this letter".
        setText(data.text);
        setOcrConfirm(true);
      } else {
        setOcrError(data?.error ?? t.error);
      }
    } catch {
      setOcrError(t.error);
    } finally {
      setOcrLoading(false);
    }
  }

  async function onSubmit(e: React.FormEvent) {
    e.preventDefault();
    if (!text.trim() || loading) return;
    setLoading(true);
    setError(false);
    setResult(null);
    setOcrError(null);
    setOcrConfirm(false);
    try {
      const res = await fetch("/api/interpret", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ text, lang }),
      });
      const data = (await res.json()) as InterpretResponse;
      setResult(data);
    } catch {
      setError(true);
    } finally {
      setLoading(false);
    }
  }

  function reset() {
    setResult(null);
    setText("");
    setError(false);
    setOcrError(null);
    setOcrConfirm(false);
  }

  if (result?.kind === "emergency") {
    return <EmergencyCard card={result.card} />;
  }

  return (
    <section className="w-full max-w-device space-y-4">
      <div className="flex items-center justify-between">
        <h2 className="text-lg font-bold text-slate-900">{t.title}</h2>
        <div className="flex overflow-hidden rounded-full border border-slate-300 text-sm">
          <button
            type="button"
            onClick={() => setLang("en")}
            className={`px-3 py-1 ${lang === "en" ? "bg-slate-900 text-white" : "text-slate-600"}`}
            aria-pressed={lang === "en"}
          >
            EN
          </button>
          <button
            type="button"
            onClick={() => setLang("zh")}
            className={`px-3 py-1 ${lang === "zh" ? "bg-slate-900 text-white" : "text-slate-600"}`}
            aria-pressed={lang === "zh"}
          >
            中文
          </button>
        </div>
      </div>

      <p className="text-sm text-slate-600">{t.subtitle}</p>

      <form onSubmit={onSubmit} className="space-y-3">
        <input
          ref={fileInputRef}
          type="file"
          accept="image/*"
          capture="environment"
          onChange={onPhotoChosen}
          className="hidden"
          aria-hidden="true"
          tabIndex={-1}
        />
        <button
          type="button"
          onClick={() => fileInputRef.current?.click()}
          disabled={ocrLoading || loading}
          className="w-full rounded-xl border border-slate-300 px-4 py-3 text-base font-semibold text-slate-700 disabled:opacity-40"
        >
          {ocrLoading ? t.photoReading : `📷 ${t.photo}`}
        </button>
        <p className="text-center text-xs text-slate-400">{t.photoPrivacy}</p>

        {ocrError && (
          <div className="space-y-2 rounded-lg bg-amber-50 p-3">
            <p className="text-sm text-slate-800">{ocrError}</p>
            <p className="text-sm text-slate-600">{t.photoTypeInstead}</p>
            <button
              type="button"
              onClick={() => fileInputRef.current?.click()}
              className="text-sm font-semibold text-slate-700 underline"
            >
              {t.photoRetake}
            </button>
          </div>
        )}

        {ocrConfirm && (
          <p className="rounded-lg bg-blue-50 p-3 text-sm text-slate-800">{t.photoConfirm}</p>
        )}

        <textarea
          value={text}
          onChange={(e) => {
            setText(e.target.value);
            setOcrConfirm(false);
          }}
          placeholder={t.placeholder}
          rows={5}
          className="w-full resize-none rounded-xl border border-slate-300 p-3 text-base text-slate-900 focus:border-slate-500 focus:outline-none"
        />
        <button
          type="submit"
          disabled={loading || !text.trim()}
          className="w-full rounded-xl bg-slate-900 px-4 py-3 text-base font-semibold text-white disabled:opacity-40"
        >
          {loading ? t.loading : t.submit}
        </button>
      </form>

      <p className="text-center text-xs text-slate-400">{t.privacy}</p>

      {error && <p className="rounded-lg bg-red-50 p-3 text-sm text-urgent">{t.error}</p>}

      {result?.kind === "interpretation" && (
        <article className="space-y-4 rounded-2xl border-l-4 border-routine bg-white p-4 shadow-sm">
          {result.offline && (
            <p className="inline-flex items-center gap-1.5 rounded-full bg-slate-100 px-2.5 py-1 text-[11px] font-semibold text-slate-500">
              <span aria-hidden="true">●</span>
              {t.offline}
            </p>
          )}
          <div>
            <p className="text-xs font-semibold uppercase tracking-wide text-slate-400">
              {t.typeHeading}
            </p>
            <p className="mt-1 text-sm font-semibold text-slate-900">{result.document_type}</p>
          </div>

          <div>
            <p className="text-xs font-semibold uppercase tracking-wide text-slate-400">
              {t.explanationHeading}
            </p>
            <p className="mt-1 whitespace-pre-line text-base leading-relaxed text-slate-900">
              {result.explanation_native}
            </p>
          </div>

          <div className="rounded-xl bg-slate-50 p-3">
            <p className="text-xs font-semibold uppercase tracking-wide text-slate-400">
              {t.englishHeading}
            </p>
            <p className="mt-1 whitespace-pre-line text-base leading-relaxed text-slate-900">
              {result.explanation_en}
            </p>
          </div>

          <div>
            <p className="text-xs font-semibold uppercase tracking-wide text-slate-400">
              {t.stepsHeading}
            </p>
            <ol className="mt-2 list-decimal space-y-1 pl-5 text-base text-slate-900">
              {result.next_steps.map((step, i) => (
                <li key={i}>{step}</li>
              ))}
            </ol>
          </div>

          <div>
            <p className="text-xs font-semibold uppercase tracking-wide text-slate-400">
              {t.questionsHeading}
            </p>
            <ul className="mt-2 list-disc space-y-1 pl-5 text-base text-slate-900">
              {result.questions_en.map((q, i) => (
                <li key={i}>{q}</li>
              ))}
            </ul>
          </div>

          <p className="text-xs text-slate-500">
            <span className="font-semibold">{t.sourceHeading}:</span> {result.explanation_source}
          </p>

          {!result.offline && result.source && result.source !== "none" && (
            <p className="text-[11px] text-slate-400">
              {result.source === "gemini" ? t.genGemini : t.genGlm}
            </p>
          )}

          <p className="border-t border-slate-100 pt-3 text-xs font-medium text-slate-500">
            {result.disclaimer}
          </p>

          <button
            type="button"
            onClick={reset}
            className="text-sm font-semibold text-slate-600 underline"
          >
            {t.again}
          </button>
        </article>
      )}

      {result?.kind === "fallback" && (
        <article className="space-y-3 rounded-2xl border-l-4 border-soon bg-white p-4 shadow-sm">
          <p className="text-base text-slate-900">{result.message}</p>
          <p className="border-t border-slate-100 pt-3 text-xs font-medium text-slate-500">
            {result.disclaimer}
          </p>
          <button
            type="button"
            onClick={reset}
            className="text-sm font-semibold text-slate-600 underline"
          >
            {t.again}
          </button>
        </article>
      )}
    </section>
  );
}
